../acc_tb/interface.sv
../acc_tb/generator_pkg.sv
../acc_tb/refmodel_pkg.sv
../acc_tb/monitor_pkg.sv
../acc_tb/driver_pkg.sv
../acc_tb/scoreboard_pkg.sv
../acc_tb/env_pkg.sv
../acc_tb/acc_tb.sv
../rtl/acc/icb_slave.v
../rtl/acc/adder_tree_ich.v
../rtl/acc/mac_array_core.v
../rtl/acc/mac_array.v
../rtl/acc/mac_array_fsm.v
../rtl/acc/repvgg_acc_top.v
../rtl/acc/icb_master.v
../rtl/acc/gnrl_modules.v
../rtl/acc/sram_4k64.v
../rtl/acc/omap_biu.v
../rtl/acc/sram_32kb_4kx64.v
../rtl/acc/imap_buf.v
../rtl/acc/adder_tree_3x3.v
../rtl/acc/map_merger.v
../rtl/acc/weight_biu.v
../rtl/acc/psum_acc.v
../rtl/acc/imap_biu.v
../rtl/acc/main_fsm.v
../rtl/acc/basic_pe.v
../rtl/acc/systolic_array.v
../rtl/acc/mac_array_wlu.v
